[package]
name = "server"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
clap.workspace = true
crossterm.workspace = true
iroh.workspace = true
parking_lot.workspace = true
protocol.workspace = true
rand.workspace = true
ratatui.workspace = true
tokio.workspace = true
transport.workspace = true
